### ISSUE TITLE
packet logger causes the game to crash version used 1.3.2 1.20.1

### ISSUE THREAD

**Issue by or0802** [stefexec/gurkens-gadgetry-public#13]
;D
![image](https://github.com/user-attachments/assets/f3445c84-a297-462e-a1d5-0c6623db4396)

![image](https://github.com/user-attachments/assets/65720035-3b55-4f79-85cd-85bf706ca46d)
[crash-2024-08-03_12.00.42-client.txt](https://github.com/user-attachments/files/16478835/crash-2024-08-03_12.00.42-client.txt)

**Comment by stefexec** [comment]
no support for outdated versions. update your game
