### ISSUE TITLE
World Guard

### ISSUE THREAD

**Issue by Spencer123455** [stefexec/gurkens-gadgetry-public#3]
World Guard is not working on the server I am on, The server does not have a anti cheat but has world guard. The world Guard Bypass is not working for me.

**Comment by Spencer123455** [comment]
It keeps on saying you are not permitted to enter this area. I cant move when I have it activated. It keeps on teleporting me back to the location I started walking from.

**Comment by stefexec** [comment]
Can you give me some more information, your ping, server tps etc. Have you tried moving in a non-protected area? If you don't move at all, no matter the area, it is likely not an issue with my plugin but rather something serverside is preventing your movement.

**Comment by stefexec** [comment]
Closed due to issue being probably caused by an anticheat
