### ISSUE TITLE
Cannot exit the end without reloggin in instance without Gurken's Gadgetry / Gamemode Changes does not occur in client untill I relog

### ISSUE THREAD

**Issue by Slingexe** [stefexec/gurkens-gadgetry-public#4]
Using latest release

1st bug
When Gurken's Gadgetry is enabled I cannot exit the end, when relogging I am still stuck in the void
When I relog in a vanilla instance or without Gurjen's Gadgetry it fixes itself

2nd bug
When trying to change gamemode, it changes to the world / server but the client still thinks its in the first gamemode untill I relog

This video shows my client and log with the mod on top and my Vanilla instance at the bottom with log
www.youtube.com/watch?v=2D56CDf_KvY

Note: To make sure Gurken's Gadgetry was the cause, I had Gurken's Gadgetry disabled while all my other mods were enabled but I could not recreate the bug

**Comment by stefexec** [comment]
This is caused by the Fake Creative Mode Bypass/WorldBoarder Module. Thats because of how the module(s) work internally. Try turning off unneccesary modules and the problem should not be encountered anymore. If you turn them off and relog, you don't need to change instances to get out of the end.

**Comment by Slingexe** [comment]
Every gurken's gadgetry module where disabled while recording the video

**Comment by tmuaprep** [comment]
+1 for this

**Comment by Slingexe** [comment]
> +1 for this

at least it aint just me

**Comment by stefexec** [comment]
fixed in 5146df2cb0e034c03b1690a946941e9809ed021a
