### ISSUE TITLE
1.20.4

### ISSUE THREAD

**Issue by pizzav-xyz** [stefexec/gurkens-gadgetry-public#9]
please port this mod to 1.20.4

**Comment by or0802** [comment]
I did kinda port it  here are the files if you want,though I am not a programmer I just copy pasted some code and its probably worse then its ever been, there you go if you want it ;D 
[Take one of them.zip](https://github.com/user-attachments/files/16469717/Take.one.of.them.zip)
or if you want to compile it your self here is the source  code
https://github.com/or0802/gurkens-gadgetry-public/releases/tag/v1.3.2-1.20.4
don't ask for bug fixes, I am not a programmer!

**Comment by pizzav-xyz** [comment]
> I did kinda port it  here are the files if you want,though I am not a programmer I just copy pasted some code and its probably worse then its ever been, there you go if you want it ;D 
> [Take one of them.zip](https://github.com/user-attachments/files/16469717/Take.one.of.them.zip)
> or if you want to compile it your self here is the source  code
> https://github.com/or0802/gurkens-gadgetry-public/releases/tag/v1.3.2-1.20.4
> don't ask for bug fixes, I am not a programmer!
> 

Could you also try 1.21?

**Comment by stefexec** [comment]
updated to 1.21
